# Generated by Django 5.2 on 2025-05-30 04:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom'], name='fournisseur_nom_576808_idx'), models.Index(fields=['email'], name='fournisseur_email_97f379_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PARTIEL', 'Partiellement livré'), ('RECEPTIONNEE', 'Réceptionnée')], default='EN_ATTENTE', max_length=12)),
                ('facture_pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant total')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='fournisseurs.fournisseur')),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='fournisseurs.commandefournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
            ],
            options={
                'ordering': ['produit__nom'],
            },
        ),
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='fournisseurs.commandefournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionAppro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.PositiveIntegerField(blank=True, null=True)),
                ('quantite_livree', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='fournisseurs.commandefournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
            ],
        ),
        migrations.AddIndex(
            model_name='commandefournisseur',
            index=models.Index(fields=['fournisseur', 'date_commande'], name='fournisseur_fournis_e3deed_idx'),
        ),
        migrations.AddIndex(
            model_name='commandefournisseur',
            index=models.Index(fields=['statut'], name='fournisseur_statut_24664e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lignecommande',
            unique_together={('commande', 'produit')},
        ),
    ]
