# Generated by Django 5.2 on 2025-05-01 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Raison sociale')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='Date commande')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PARTIEL', 'Partiellement livré'), ('LIVRE', 'Livré')], default='EN_ATTENTE', max_length=12, verbose_name='Statut')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='fournisseurs.fournisseur')),
            ],
            options={
                'verbose_name': 'Commande fournisseur',
                'verbose_name_plural': 'Commandes fournisseur',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité commandée')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix achat')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='fournisseurs.commandefournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant payé')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='fournisseurs.commandefournisseur')),
            ],
            options={
                'verbose_name': 'Paiement fournisseur',
                'verbose_name_plural': 'Paiements fournisseur',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionAppro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception', models.DateTimeField(auto_now_add=True, verbose_name='Date réception')),
                ('quantite_livree', models.PositiveIntegerField(verbose_name='Quantité livrée')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Référence livraison')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='fournisseurs.commandefournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
            ],
            options={
                'verbose_name': 'Réception',
                'verbose_name_plural': 'Réceptions',
                'ordering': ['-date_reception'],
            },
        ),
    ]
