# Generated by Django 5.2 on 2025-05-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandefournisseur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lignecommande',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paiementfournisseur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='receptionappro',
            options={},
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='facture_pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures_achats/'),
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PARTIEL', 'Partiellement livré'), ('LIVRE', 'Livré')], default='EN_ATTENTE', max_length=12),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='date_paiement',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='receptionappro',
            name='date_reception',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receptionappro',
            name='quantite_livree',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='receptionappro',
            name='reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
