# Generated by Django 5.2 on 2025-05-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fournisseurs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receptionappro",
            name="prix_achat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
