# Generated by Django 5.2 on 2025-05-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionappro',
            name='quantite_commandee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
