# Generated by Django 5.2 on 2025-05-09 13:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_receptionappro_quantite_commandee'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandefournisseur',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PARTIEL', 'Partiellement livré'), ('LIVRE', 'Livré'), ('RECEPTIONNEE', 'Réceptionnée')], default='EN_ATTENTE', max_length=12),
        ),
    ]
