# Generated by Django 5.2 on 2025-05-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_alter_commandefournisseur_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefournisseur',
            name='facture_pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures/'),
        ),
    ]
