# Generated by Django 5.2 on 2025-05-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='level',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('DANGER', 'Urgent')], default='WARNING', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('STOCK_LOW', 'Stock bas'), ('EXPIRATION', "Produit proche de la date d'expiration"), ('PAYMENT_LATE_CLIENT', 'Retard de paiement client'), ('PAYMENT_LATE_SUPPLIER', 'Retard de paiement fournisseur'), ('ORDER_PENDING', 'Commande en attente')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['type', '-created_at'], name='alerts_aler_type_bd08d8_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_read', '-created_at'], name='alerts_aler_is_read_be931c_idx'),
        ),
    ]
