# Generated by Django 5.2 on 2025-05-01 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=6, verbose_name='Type de mouvement')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement')),
                ('reference', models.CharField(blank=True, help_text='Ex: commande fournisseur ou vente', max_length=100, verbose_name='Référence')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
            },
        ),
    ]
