# Generated by Django 5.2 on 2025-05-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('monnaie', models.CharField(choices=[('CFA', 'Franc CFA'), ('USD', 'Dollar US'), ('FGN', 'Franc Guinéen'), ('EUR', 'Euro')], default='CFA', max_length=3, verbose_name='Devise')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock actuel')),
                ('stock_minimum', models.PositiveIntegerField(default=0, verbose_name='Stock minimum')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('alerte_expiration', models.BooleanField(default=True, verbose_name='Alerter avant expiration')),
                ('delai_alerte_expiration', models.IntegerField(default=90, help_text="Nombre de jours avant expiration pour déclencher l'alerte", verbose_name="Délai d'alerte (jours)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['date_expiration'], name='produits_pr_date_ex_e1f0ac_idx'), models.Index(fields=['stock'], name='produits_pr_stock_990f2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TauxChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise_source', models.CharField(choices=[('CFA', 'Franc CFA'), ('USD', 'Dollar US'), ('FGN', 'Franc Guinéen'), ('EUR', 'Euro')], max_length=3, verbose_name='Devise source')),
                ('devise_cible', models.CharField(choices=[('CFA', 'Franc CFA'), ('USD', 'Dollar US'), ('FGN', 'Franc Guinéen'), ('EUR', 'Euro')], max_length=3, verbose_name='Devise cible')),
                ('taux', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Taux')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Taux de change',
                'verbose_name_plural': 'Taux de change',
                'unique_together': {('devise_source', 'devise_cible')},
            },
        ),
    ]
