# Generated by Django 5.2 on 2025-05-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('monnaie', models.CharField(choices=[('CFA', 'Franc CFA'), ('USD', 'Dollar US'), ('FGN', 'Franc Guinéen')], default='CFA', max_length=3, verbose_name='Devise')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock initial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
    ]
